server:
  port: 9001
  address: 0.0.0.0
spring:
#   application:
#     name: system
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://192.168.205.232:13306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:eversec123098}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
#   cloud:
#     nacos:
#       discovery:
#         server-addr: ${NACOS_SERVERADDR:http://192.168.205.232:8848}
#       config:
#         server-addr: ${NACOS_SERVERADDR:http://192.168.205.232:8848}
#         file-extension: yaml
  redis:
    host: ${REDIS_HOST:192.168.205.232} # Redis服务器地址
    database: ${REDIS_DATABASE:0} # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:16379} # Redis服务器连接端口
    password: ${REDIS_PASSWORD:eversec123!@#}  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis-plus:
  mapperLocations:
    - classpath:mapper/*/*.xml

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# redis缓存配置
redis:
  database: mall
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时

logging:
  level:
    root: info
    com.yy.system: debug

# LogStash访问,elk日志收集
logstash:
  host: ${LOGSTASH_HOST:192.168.205.232}

feign:
  hystrix:
    enabled: true # 开启断路器 
  okhttp:
    enabled: true  #feign使用okhttp去调用微服务
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000

ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）