server:
  port: 9001
spring:
  application:
    name: system
  profiles:
    active: dev #采用dev配置文件信息
#   datasource:
#     url: jdbc:mysql://192.168.205.232:13306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#     username: root
#     password: eversec123098
#     druid:
#       initial-size: 5 #连接池初始化大小
#       min-idle: 10 #最小空闲连接数
#       max-active: 20 #最大连接数
#       web-stat-filter:
#         exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#       stat-view-servlet: #访问监控网页的登录用户名和密码
#         login-username: druid
#         login-password: druid
#   redis:
#     host: 192.168.205.232 # Redis服务器地址
#     database: 0 # Redis数据库索引（默认为0）
#     port: 16379 # Redis服务器连接端口
#     password: eversec123!@#  # Redis服务器连接密码（默认为空）
#     timeout: 3000ms # 连接超时时间（毫秒）
#   servlet:
#     multipart:
#       enabled: true #开启文件上传
#       max-file-size: 10MB #限制文件上传大小为10M
# mybatis:
#   mapper-locations:
#     - classpath:mapper/*/*.xml

# # redis缓存配置
# redis:
#   database: mall
#   key:
#     admin: 'ums:admin'
#   expire:
#     common: 86400 # 24小时

# logging:
#   path: ${user.dir}/logs
#   file: ${logging.path}/system.log
#   level:
#     root: info
#     com.yy.system: debug

# # LogStash访问,elk日志收集
# logstash:
#   host: 192.168.205.232